### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mark03** [polimi-cheatsheet/PPL-cheatsheet#1]
- [x] Exception handling in scheme using call/cc
- [x] Examples of application of foldl/foldr
- [x] FIFO reliability of Erlang
- [x] Scheme list functions
